from flask import Blueprint, render_template
web_bp=Blueprint('web',__name__)
@web_bp.get('/')
def index(): return render_template('index.html')
@web_bp.get('/login')
def login_page(): return render_template('login.html')
@web_bp.get('/register')
def register_page(): return render_template('register.html')
@web_bp.get('/dashboard')
def dashboard(): return render_template('dashboard.html')
@web_bp.get('/admin')
def admin_page(): return render_template('admin.html')
@web_bp.get('/operator')
def operator_page(): return render_template('operator.html')
